from .base import *


DEBUG = False

STATIC_ROOT = BASE_DIR.parent.child("staticfiles")

ALLOWED_HOSTS = ['.3stepstaken.com']

# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_SSL_REDIRECT = True

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True

X_FRAME_OPTIONS = 'DENY'